### ISSUE TITLE
Release Channels

### ISSUE THREAD

**Issue by Starefossen** [nais/unleasherator#427]
Release Channel will make it possible to automatically upgrade instances when new versions become available:

```yaml
apiVersion: unleash.nais.io/v1
kind: ReleaseChannel
metadata:
  name: stable
spec:
  image: repo.example.com/my/image:tag
  matchLabels:
    unleash.nais.io/release-channel: stable
  strategy:
    maxSurge: 2
    canary:
      enabled: true
      matchLabels:
       unleash.nais.io/canary: true
```

Reconciler:

* finds all matching Unleash instances
* starts with the ones maching `ReleaseChannel.spec.strategy.canary.matchLabels` 
* runs in parallel according to `ReleaseChannel.spec.strategy.maxSurge` 
* updates `Unleash.spec.customImage` waiting for rollout to succeed (depends on #260) 
* stop rollout if an Unleash instance fails and marks `ReleaseChannel` as failed

Questions:

* [ ] how to prevent customImage from being "reset" by the user
  * [ ] default to `ReleaseChannel` when no `Unleash.spec.customImage` is set
