### ISSUE TITLE
Add support for RemoteUnleash objects

### ISSUE THREAD

**Issue by Starefossen** [nais/unleasherator#59]
## Motivation

The purpose of the `RemoteUnleash` CRD is a config object to allow Unleasherator to manage `ApiTokens` for Unleash instances managed outside the cluster. This is useful when you are using Unleash Hosted or have another cluster where the Unleash instance lives but want to be able to automate `ApiToken` for your application.

## Implementation

```yaml
apiVersion: unleash.nais.io/v1alpha1
kind: RemoteUnleash
spec:
  # The address for the Unleash API server
  apiAddress: https://unleash.nais.io/api

  # The name of the secret containing the API token
  apiTokenSecretName: unleash-api-token

  # The key in the secret containing the API token
  apiTokenSecretKey: token

```
